# Generated by Django 4.0.6 on 2022-07-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.company')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employes')),
            ],
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='game',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='player',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerScore',
        ),
        migrations.AddField(
            model_name='company',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employes'),
        ),
    ]
